# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c8798e090d8972c2802280c57ae732154401c7eef13f536a269ea08a1ec7058ac49fb9b22f45e1bf6a102f9107e2b17d38d1b104d8a0d3baa532daaa628dc19

test:
  secret_key_base: e7f0b894622b8b614de1abc89f80d80127e17ad17ff1d0215153a90af2a2dfccc6c03a1b0e7df7f42711a9c938b1f63a4ab71043a09a4f754d8830f3a61d6f69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
